### ISSUE TITLE
Mettre à jour gtfs-to-geojson

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-tools#19]
Après que https://github.com/rust-transit/gtfs-to-geojson/pull/8 soit mergée

Pour bénéficier du correctif permettant d'avoir une couleur par défaut quand la couleur est renseignée comme vide

**Comment by thbar** [comment]
La PR a été remplacée par https://github.com/rust-transit/gtfs-to-geojson/pull/9 et mergée.

Je vais mettre à jour ce matin.

**Comment by thbar** [comment]
Traité dans #19, je vais faire une release et remonter la chaîne.
